### ISSUE TITLE
Works well but needs improvement

### ISSUE THREAD

**Issue by merts1** [Leaf48/YOLOv5-Models-For-Valorant#1]
Like all the other models, it is probably trained on youtube edits and model sometimes can not differentiate between teammates and enemies. Also most of those youtube clips consist of kills where you face the enemy, that's why these models fail to recognize enemies when you're behind them.

I think there is no need for improvement on recognition part, however there is a need to add negative samples on training phase with teammates on the background.

I mean I would like to help this project too, I'm just writing this not as a criticisizm but as a way to encourage a better model.

Reall cool work!

edit: I have only tested [valorant-v6.pt], [valorant-n.pt] , [valorant-bot.pt] versions btw.

**Comment by Leaf48** [comment]
Actually, models are based on images from actual play, not YouTube.

And I'm already aware of the problem that almost models are unable to recognize between enemy and teammate. But I won't make any changes to **valorant-v** and **valorant-n** series.

I gonna make another version that can recognize. And I will be distributing a dataset that was used for **valorant-v** and **valorant-n** series.

Thanks for your support.

**Comment by merts1** [comment]
> 
> And I will be distributing a dataset that was used for **valorant-v** and **valorant-n** series.
> 

That would be a great contribution.

**Comment by merts1** [comment]
https://mega.nz/file/XM4DgCSK#-esZ_rkH8val8SuB8nCiGuw4bpHITZVZjYaxYO6Tcb8

This is another data collection if you want to train on your model.

**Comment by Leaf48** [comment]
Thanks for sharing your data collection. 
It may be used to train 😄

**Comment by Leaf48** [comment]
I’ve looked your dataset over. 
It would be very helpful for training. 

Thanks 😄

**Comment by Leaf48** [comment]
As you can see, there are two annotations in your shared file in clip2(1).txt.
I can understand one of the annotations that is "enemy", but I cannot understand the other.
What is it?

**Comment by merts1** [comment]
> As you can see, there are two annotations in your shared file in clip2(1).txt. I can understand one of the annotations that is "enemy", but I cannot understand the other. What is it?

can see that by openin the label file with notepad

https://imgur.com/a/RG0ZfQP

**Comment by Leaf48** [comment]
I see! 
Thanks 👍🏻

**Comment by merts1** [comment]
> I see! Thanks 👍🏻

you're welcome, I'm always open to help this project

**Comment by Leaf48** [comment]
I released a dataset.
[Check it out.](https://github.com/Leaf48/YOLOv5-Models-For-Valorant/releases/tag/dataset)

**Comment by merts1** [comment]
I will try to create a color map ai detection method by combining these data, I think that would help the model.

**Comment by Leaf48** [comment]
It sounds great. 
I'm looking forward to it!

**Comment by danielyx-z** [comment]
> I released a dataset. [Check it out.](https://github.com/Leaf48/YOLOv5-Models-For-Valorant/releases/tag/dataset)

Hi, im wondering if you could post a dropbox/alternative download link for the dataset? I couldn't seem to be able to download them on github, as it says page not found. Thanks!

**Comment by Leaf48** [comment]
https://github.com/Leaf48/YOLOv5-Models-For-Valorant/releases
