### ISSUE TITLE
No detections Found

### ISSUE THREAD

**Issue by danielyx-z** [Leaf48/YOLOv5-Models-For-Valorant#2]
Hello, I trained 400 more epochs with the valorant-v10.pt weights using --img 736 --batch 24 --epochs 400 --data valorant.yaml --weights valorant-v10.pt --device 0 however, after training it seems to work worse than your weights. It does not detect anything when I load a torch model and show the results. The data I used was downloaded from your repository, so I don't know why this is. Do I need a higher batch size? Or more epochs? My GPU is a 1660ti so it cannot handle batch size more than 24. What settings did you use when training the model? Thanks so much!
![image](https://user-images.githubusercontent.com/79776986/174492653-da06e3c0-1751-4ede-8873-e85f7e716ed0.png)
![image](https://user-images.githubusercontent.com/79776986/174492671-ea5356c1-7d2b-438c-9214-8cfd1aed8865.png)

**Comment by Leaf48** [comment]
1.You had better increase batch-size. If possible, it would be better to set batch-size to 80 or more. 
I encourage you to try yolov5s as weight. 

2.Try using [dataset](https://github.com/Leaf48/YOLOv5-Models-For-Valorant/releases/tag/dataset-v1.0) labeled only "enemy". 
Your dataset is included some images labeled not only "enemy" but also "head". 
It may have confused your machine learning. 

My env:
Weight: yolov5s or valorant-v8.pt(It's the best precise of models)
Epoch: 300 to 500
Batch-size: 80 or more
Google Colab Pro

Have fun with your machine learning 😄

**Comment by danielyx-z** [comment]
Thanks so much! I will try the dataset with only enemy labelled and valorant-v8.pt. 🥰 Just curious: How did you manage to have the v10 model detect enemy_head as well as enemy? Would I be able to label 'head' on your dataset and merge it with my current to have it detect both? Right now my class names are ['body', 'head'] so I am not sure if I have to name them enemy, enemy_head as long as the class values [0, 1] stay the same.   (I can also give you the newly labelled data if it works to merge with valorant-v11.pt)
