### ISSUE TITLE
Problem with the dtc

### ISSUE THREAD

**Issue by Shadowlo21** [Leaf48/YOLOv5-Models-For-Valorant#3]
_### hi how are u i get problem that he not dtc all the enemy 
like i try all ur wights and its same i hope u can help me and if u could give me ur discord to dm u and thank u and nice work_

**Comment by Leaf48** [comment]
Hi
I do no individually chat on discord.
If you had a problem, I could help you here.  

Could you show me your Python file?

**Comment by Shadowlo21** [comment]
yess i can 
thats the file :
from socket import timeout
import time
import torch
import cv2
import numpy as np
from mss import mss
import keyboard
import serial



model = torch.hub.load(r'C:\Users\Shady\Desktop\Valorant Aim\Scripts\yolov5-master', 'custom', path=r'C:\Users\Shady\Desktop\Valorant Aim\Scripts\best.pt', source='local')
arduino = serial.Serial("com4", "115200", timeout = .1)

def SendCordinates(code):
    code = str(code)
    arduino.write(str.encode(code))

def CalculateDistance(x,y): ## distance : (-100,100) -> "n,100,p,100*"
    if x < 0:
        x *=-1
        x_d = "n"
    else:
        x_d = "p"
    if y < 0:
        y*=-1
        y_d = "n"
    else:
        y_d = "p"

    x_v = int(x/5)
    y_v = int(y/5)
    code = x_d + "," + str(x_v) + "," + y_d + "," + str(y_v) + "*"
    #print(code)
    return code

with mss() as sct:
    monitor = {"top": 221, "left": 640, "width": 450, "height":600}

    while(True):
        screenshot = np.array(sct.grab(monitor))
        results = model(screenshot, size=640)
        df= results.pandas().xyxy[0]
        try:
            xmin = int(df.iloc[0,0])
            ymin = int(df.iloc[0,1])
            xmax = int(df.iloc[0,2])
            ymax = int(df.iloc[0,3])

            head_level = (int(xmin + (xmax - xmin) / 2), int(ymin + (ymax - ymin) / 8))
            cv2.circle(screenshot, head_level, 4, (0,255,0), thickness = -1)
            cv2.rectangle(screenshot, (xmin, ymin), (xmax, ymax), (255,0,0), 2)

            distance = (head_level[0] - 320, head_level[1] -320)
            
            if keyboard.is_pressed('0'):
                code = CalculateDistance(int(distance[0]), int(distance[1]))
                SendCordinates(code)
                time.sleep(0.03)
        except:
            print("",end="")

        cv2.imshow("frame", screenshot)
        if(cv2.waitKey(1) == ord('q')):
            cv2.destroyAllWindows()
            break

**Comment by Leaf48** [comment]
Change from
```
model = torch.hub.load(r'C:\Users\Shady\Desktop\Valorant Aim\Scripts\yolov5-master', 'custom', path=r'C:\Users\Shady\Desktop\Valorant Aim\Scripts\best.pt', source='local')
```
To
```
model = torch.hub.load(r'C:\Users\Shady\Desktop\Valorant Aim\Scripts\yolov5-master', 'custom', path=r'C:\Users\Shady\Desktop\Valorant Aim\Scripts\valorant-v8.pt', source='local')
```

You need to install `valorant-v8.pt` form my repo and put it same directory.

*I don't really recommend naming folder included spaces.

**Comment by Shadowlo21** [comment]
ok thank u i will try this
