### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by thommy51** [Leaf48/YOLOv5-Models-For-Valorant#7]
Hey mate, I appreciate your work. Could you add me on discord? I have some questions :)

kan0#6997

**Comment by Leaf48** [comment]
Hi. What's your problem? I will answer your questions here as long as I can.

P.S. I don't have discord or any SNS account for contacts. Sorry for that.

**Comment by minkyujung00** [comment]
can i get labeled dataset for yolov7???
