### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by chambertv** [Leaf48/YOLOv5-Models-For-Valorant#9]
I have a dataset of 4000 images, are you interested?

**Comment by Leaf48** [comment]
Hi. 
I always look for more datasets. Of course I'm interested in your datasets.

**Comment by chambertv** [comment]
sorry for not answering I forgot xD, my discord chambertc#6728

**Comment by anzenchitai** [comment]
I am also looking to collaborate. Add rawados#7800
